spring.application.name=auth-service
spring.profiles.active=dev
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/${spring.application.name}.log
logging.level.edu.eci.arsw.pixelplatform.auth=DEBUG
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB
canvas-service.base-url=${CANVAS_SERVICE_BASE_URL:http://localhost:8082}
