server.port=8081
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/auth_db
spring.datasource.username=pixel_user
spring.datasource.password=pixel_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.data.redis.host=localhost
spring.data.redis.port=6379
jwt.secret=dev-secret-key-pixelplatform-auth-service-arsw-2026
jwt.expiration-ms=86400000
cors.allowed-origins=http://localhost:5173
canvas-service.base-url=${CANVAS_SERVICE_BASE_URL:http://localhost:8082}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_APP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.config.import=optional:classpath:application-dev-local.properties
app.upload-dir=./uploads/avatars
