spring.application.name=signaling-service
spring.profiles.active=dev
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/${spring.application.name}.log
logging.level.edu.eci.arsw.pixelplatform.signaling=DEBUG
jwt.secret=${JWT_SECRET:dev-secret-key-pixelplatform-auth-service-arsw-2026}
