server.port=8083
canvas-service.base-url=http://localhost:8082
cors.allowed-origins=http://localhost:5173
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/chat_db
spring.datasource.username=pixel_user
spring.datasource.password=pixel_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
