spring.application.name=canvas-service
spring.profiles.active=dev
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.level.edu.eci.arsw.pixelplatform.canvas=DEBUG
canvas.width=100
canvas.height=100
canvas.cooldown-seconds=5
